### ISSUE TITLE
[Feat]: Make the marketplace public

### ISSUE THREAD

**Issue by vinzvinci** [web3community/DEV-NFT#48]
### Detailed Description

I think this has been discussed before, so I make this issue so we don't forget it.

## What it will be like?
- Not login
   - They can't buy the NFT
   - View only
- If the user login
   -  They can able to buy the NFT

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KukretiShubham** [comment]
This was resolved previously, you can check `devnft.xyz/dashboard` this will show marketplace without login. Let it open to remind ourselves as the page is not exposed on landing page.

**Comment by vinzvinci** [comment]
> This was resolved previously, you can check `devnft.xyz/dashboard` this will show marketplace without login. Let it open to remind ourselves as the page is not exposed on landing page.

Oh okay, I am closing this issue now :D

**Comment by KukretiShubham** [comment]
I think you create another. With the title `make dashboard accessible through landing page`

**Comment by vinzvinci** [comment]
> I think you create another. With the title `make dashboard accessible through landing page`

I will do it 🎉
