### ISSUE TITLE
[Bug]: Login Session Issue in Mobile View

### ISSUE THREAD

**Issue by AbhinavMV** [web3community/DEV-NFT#54]
### Detailed Description

I found this error in this project where I have logged in to the website but if i switch to mobile view it shows the login option again but going back to desktop view it shows i am logged in again... (Not everyone might encounter this but still looks like an error)

### Expected Behavior

I expected that it will be logged in even if i switch the screen size

### How can someone reproduce the behavior?

1. Go to the website on desktop view and login with your cred after this you would be able to see the account on navbar.
![image](https://user-images.githubusercontent.com/35369843/147388423-e302f2f3-61a2-4075-a188-024bf7a23543.png)
2. Do right click then inspect and reduce screen size so you can see the hamburger icon. 
3. Now click on icon. You will see the option to login again.
![image](https://user-images.githubusercontent.com/35369843/147388445-952b83de-6911-4fae-9004-826ea0b975a3.png)
4. Finally if you go back to desktop view again, you will see that you are already logged in.

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Anything else?

This is looks amazing and helpful. Shout out to the whole team for this awesome project. 😄

**Comment by vinzvinci** [comment]
Hey Abhinav, great to see you here :D

Thanks for raising this issue, are you going to take this issue?

**Comment by AbhinavMV** [comment]
Yes i would like to give it a try 😄

**Comment by vinzvinci** [comment]
Cool!
